# Generated by Django 5.1 on 2024-09-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='is_Active',
        ),
        migrations.AlterField(
            model_name='release',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Выберите продукт', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.DecimalField(decimal_places=2, default=0.01, help_text='Введите номер версии продукта', max_digits=4, verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version_name',
            field=models.CharField(blank=True, help_text='Введите имя версии продукта', max_length=100, null=True, verbose_name='название версии'),
        ),
        migrations.AddField(
            model_name='release',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Укажите является ли версия активной'),
        ),
    ]
